CREATE DATABASE ${DATABASE_NAME};

USE ${DATABASE_NAME};

CREATE TABLE ${DATABASE_TABLENAME} (
  username VARCHAR(50) PRIMARY KEY,
  password VARCHAR(255) NOT NULL
);

CREATE USER '${DATABASE_USERNAME}'@'%' IDENTIFIED BY '${DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${DATABASE_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON ${DATABASE_TABLENAME} TO '${DATABASE_USERNAME}'@'%';